# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tinysets
email:
description: >- # this means to ignore newlines until "baseurl:"
  Math in game program.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true
locale: "zh-CN"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 1000 # amount of posts to show
paginate_path: /page:num/
timezone: "Asia/Shanghai" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "tinysets"
  avatar : "/assets/images/google.png"
  bio    : "Less is more!"
  location : "China,Shanghai"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tinysets"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tinysets"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"


search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : algolia # lunr (default), algolia
algolia:
  application_id         : 8HGFCAY8LR # YOUR_APPLICATION_ID
  index_name             : prod_tinysets # YOUR_INDEX_NAME
  search_only_api_key    : 35c37f13ae9be148b39f5054f7ce3c4e # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : true # true (default), false

comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "staticman_v2", "staticman", "utterances", "custom"
  disqus:
    shortname            : "tinysets"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: false
      comments: false
      share: false
      related: false
      comments: false
      author_profile: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
